### PR TITLE
Change the slow test test so it starts 3 threads at once

### PR DESCRIPTION
**Pull request by dcollins53**
Noticed that the parallel test wasn't always passing, I think there was a race condition in creating the threads (which the cached thread pool creates on demand).  Migrating to a fixed thread pool with 3 threads, means the thread creation is done first, and that seemed to remove all the non-determinism from the test case

### CODE REVIEW

**Comment by dcollins53** [comment]
@romseygeek this is more about whether this makes sense to pull back to the core luwak release (which would need to be a different pull request I know, but I wasn't sure what the "trunk" of luwak was these days.

**Comment by romseygeek** [comment]
This is fine, I think.  Out of interest, what did the failures look like?

**Comment by dcollins53** [comment]
Hmm, just tried to reproduce and of course it works fine now (even with the old code)....  I'll put this on hold then until I can prove we need it

**Comment by dcollins53** [comment]
Going to abandon this, the issue I could have sworn needed fixing appears to have disappeared, so there is no real justification for this change.

**Pull request closed without merging**
